// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// adaboost
NumericMatrix adaboost(NumericMatrix features, NumericMatrix outcome_index, NumericVector outcomes, NumericVector& weights, int iterations);
RcppExport SEXP _sboost_adaboost(SEXP featuresSEXP, SEXP outcome_indexSEXP, SEXP outcomesSEXP, SEXP weightsSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type outcome_index(outcome_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcomes(outcomesSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaboost(features, outcome_index, outcomes, weights, iterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sboost_adaboost", (DL_FUNC) &_sboost_adaboost, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sboost(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
