# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost <- function(features, ordered_index, outcomes, categorical, iterations) {
    .Call(`_sboost_adaboost`, features, ordered_index, outcomes, categorical, iterations)
}

predict <- function(features, classifier) {
    .Call(`_sboost_predict`, features, classifier)
}

assess <- function(features, outcomes, classifier) {
    .Call(`_sboost_assess`, features, outcomes, classifier)
}

