# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost <- function(features, ordered_index, outcomes, iterations) {
    .Call('_sboost_adaboost', PACKAGE = 'sboost', features, ordered_index, outcomes, iterations)
}

find_classifier_contingency <- function(features, outcomes, classifier) {
    .Call('_sboost_find_classifier_contingency', PACKAGE = 'sboost', features, outcomes, classifier)
}

