# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost <- function(features, outcome_index, outcomes, weights) {
    .Call('_sboost_adaboost', PACKAGE = 'sboost', features, outcome_index, outcomes, weights)
}

