#' sboost Validation Function
#'
#' A k-fold cross validation algorithm for sboost.
#'
#' @param features feature set data.frame.
#' @param outcomes outcomes corresponding to the features.
#' @param iterations number of boosts.
#' @param k_fold number of cross-validation subsets.
#' @param positive is the positive outcome to test for; if NULL, the first in
#'                 alphebetacal order will be chosen
#' @return An \emph{sboost_validation} S3 object containing:
#' \describe{
#'   \item{\emph{training_statistics}}{Mean and standard deviations for test statistics
#'         generated by \code{\link{sboost_assess}} for each of the training sets.}
#'   \item{\emph{testing_statistics}}{Mean and standard deviations for test statistics
#'         generated by \code{\link{sboost_assess}} for each of the testing sets.}
#'   \item{\emph{training_assessments}}{sboost \emph{sboost_assessment} objects
#'         used to generate training_statistics.}
#'   \item{\emph{testing_assessments}}{sboost \emph{sboost_assessment} objects
#'         used to generate testing_statistics.}
#'   \item{\emph{classifier_list}}{sboost \emph{sboost_classifier} objects
#'         created from training sets.}
#'   \item{\emph{outcomes}}{Shows which outcome was considered as positive and which negative.}
#'   \item{\emph{k_fold}}{number of testing and training sets used in the validation.}
#'   \item{\emph{call}}{Shows the parameters that were used for validation.}
#' }
#' @seealso \code{\link{sboost}} documentation.
#' @examples
#' # malware
#' sboost_validate(malware[-1], malware[1], iterations = 10, k_fold = 4, positive = 1)
#'
#' # mushrooms
#' sboost_validate(mushrooms[-1], mushrooms[1], iterations = 10, k_fold = 4, positive = "p")
#' @export
sboost_validate <- function(features, outcomes, iterations = 1, k_fold = 6, positive = NULL) {

  # PREPARE INPUT
  # --------------------------------------------------------------------------------

  # test and prepare features and outcomes
  if (is.data.frame(outcomes)) outcomes <- outcomes[[1]]
  processed_features <- process_feature_input(features)
  categorical <- find_categorical(features)
  otcm_def <- check_positive_value(outcomes, positive)
  processed_outcomes <- process_outcome_input(outcomes, features, otcm_def)

  # create variables
  classifier_list <- list();
  training_assessments <- list();
  testing_assessments <- list();
  rows = nrow(features);


  # MAIN VALIDATION LOOP
  # --------------------------------------------------------------------------------
  for (i in 1:k_fold) {
    training <- -(((i - 1) / k_fold) * rows):-((i / k_fold) * rows)
    testing <- ((((i - 1) / k_fold) * rows) + 1):((i / k_fold) * rows)

    # create classifier
    classifier_list[[i]] <- make_classifier(processed_features[training, ], processed_outcomes[training], categorical, iterations)

    # test classifier
    training_assessments[[i]] <- make_assessment(processed_features[training, ], processed_outcomes[training], classifier_list[[i]])
    testing_assessments[[i]] <- make_assessment(processed_features[testing, ], processed_outcomes[testing], classifier_list[[i]])

    # prepare output
    classifier_list[[i]] <- process_classifier_output(classifier_list[[i]], features[training, ], outcomes[training], otcm_def, match.call())
    training_assessments[[i]] <- process_assessment_output(training_assessments[[i]], classifier_list[[i]], match.call())
    testing_assessments[[i]] <- process_assessment_output(testing_assessments[[i]], classifier_list[[i]], match.call())
  }

  validation <- process_validation_output(training_assessments, testing_assessments, classifier_list, k_fold, match.call())

  return(validation)
}





